version: '3.9'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - myNet

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - myNet

networks:
  myNet:

volumes:
  mariadb-vol: 

