version: '3.9'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - myNet
    volumes:
      - mariadb-vol:/var/lib/mysql
    expose: "3306"

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - myNet
    ports: "443:443"

networks:
  myNet:

volumes:
  mariadb-vol:
    driver: local
    driver_opts:
      type: local
      o: "bind"
      device: /home/debian12/data

